apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  BACKEND_URL: "{{ .Values.configmap.backendUrl }}"
  ACCESS_KEY_ID: "{{ .Values.configmap.accessKeyId }}"
