apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  BACKEND_URL: "{{ .Values.configmap.backendUrl }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.configmap.accessKeyId }}"
  BUCKET_NAME: "{{ .Values.configmap.bucketName }}"
  AWS_S3_ENDPOINT: "{{ .Values.configmap.s3Endpoint }}"
