apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- range $k, $v := .Values.cronjob.labels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        spec:
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
          - name: {{ .Values.cronjob.name }}
            image: {{ .Values.cronjob.image }}
            imagePullPolicy: {{ .Values.cronjob.imagePullPolicy }}
            env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: woog.backend-db.credentials.postgresql.acid.zalan.do
            envFrom:
              - secretRef:
                  name: {{ .Values.secret.name }}
              {{- range $secretName := .Values.cronjob.secrets }}
              - secretRef:
                  name: {{ $secretName }}
              {{- end }}
              - configMapRef:
                  name: {{ .Values.configmap.name }}
              {{- range $configmapName := .Values.cronjob.configmaps }}
              - configMapRef:
                  name: {{ $configmapName }}
              {{- end }}
            resources:
              requests:
                cpu: {{ .Values.cronjob.requests.cpu }}
                memory: {{ .Values.cronjob.requests.memory }}
              limits:
                cpu: {{ .Values.cronjob.limit.cpu }}
                memory: {{ .Values.cronjob.limit.memory }}
