name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}

  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/woog-life/graphing:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/woog-life/graphing:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_docker
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - run: sed -i -e "s/__ACCESS_KEY_ID__/${{ secrets.EXOSCALE_WOOGLIFE_PUTOBJECT_ACCESS_KEY }}/g" values.yaml
      - run: sed -i -e "s/__SECRET_ACCESS_KEY__/${{ secrets.EXOSCALE_WOOGLIFE_PUTOBJECT_ACCESS_SECRET }}/g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade graphing . --install --namespace=wooglife --atomic
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
